apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-scheduler-view
  namespace: default
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
  # `edit` is a built-in cluster role. more info about these can be found here:
  # https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles
subjects:
- kind: ServiceAccount
  name: node-scheduler
  namespace: default
