name: CI/CD
on: push
jobs:
  test_and_release:
    name: CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        # TODO move to running full test suite.
        # run: go test ./...
        run: go test ./pkg/runplugin
      - name: Build tools
        if: startsWith(github.ref, 'refs/tags/')
        run: ./build.sh
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            runplugin-amd64
            runplugin-arm64
            pluginctl-amd64
            pluginctl-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
